### ISSUE TITLE
Activities/notifications number and dropdown 

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-surfer#124]
Let's have number on bell like [this](https://stackoverflow.com/questions/5747863/easiest-css-for-facebook-style-red-notifications):
![image](https://user-images.githubusercontent.com/3015990/42779817-2cc2e23e-894a-11e8-8043-4e18956cbfe9.png)

and have quick access drop down to see latest 5 or 10 of them with button to see all

![image](https://user-images.githubusercontent.com/3015990/42779713-e4bc7388-8949-11e8-84dd-475d53f2d91b.png)

**Comment by feruzm** [comment]
@fildunsky have you had some mockups ideas for dropdown here?

**Comment by fildunsky** [comment]
![notifications_popup2_1](https://user-images.githubusercontent.com/32987666/42865684-173934e8-8a73-11e8-9f28-2f108923d043.png)

### 3 digits numbers 
- When there are more than 99 notifications then let's show only white dot instead of number

![notifications_popup2_2](https://user-images.githubusercontent.com/32987666/42865812-84533c2c-8a73-11e8-91ab-26c028098406.png)

**Comment by fildunsky** [comment]
It could be red as well. I think it's organic for users. Red dot looks like a notification asking to pay attention to it. What do you say?

![notifications_popup2_3](https://user-images.githubusercontent.com/32987666/42865974-f5d2d696-8a73-11e8-81f4-6673a800ccb0.png)

**Comment by fildunsky** [comment]
Yeah, super. But for 3 dots better to use bullets from unicode which are aligned in center

**Comment by talhasch** [comment]
Activities popover implemented.

![image](https://user-images.githubusercontent.com/1177676/43037400-8062e654-8d15-11e8-9b54-28a572e14225.png)

**Comment by fildunsky** [comment]
Looking great! I've found one small bug. When the popover is active (opened) you can not access userhead menu (top right avatar menu) because it opens in the background under notification popover. 

Check the screen below please:

<img width="1112" alt="2018-07-21 19 37 08" src="https://user-images.githubusercontent.com/32987666/43038231-459b82fc-8d1e-11e8-913c-f5c63adf7361.png">

**Comment by fildunsky** [comment]
### Our "native" variant for now

![01](https://user-images.githubusercontent.com/32987666/43038294-58340a5a-8d1f-11e8-9cb0-bab80e153794.png)

### Small red dots

![02](https://user-images.githubusercontent.com/32987666/43038292-5812d4de-8d1f-11e8-8f9d-cd30d8db4066.png)

### Facebook-like unread

I like this variant more but seems we have to add more space in between notifications then. Now they look too close to each other here.

![03](https://user-images.githubusercontent.com/32987666/43038291-57f2ea5c-8d1f-11e8-8c04-5ab5fc9d20af.png)

**Comment by talhasch** [comment]
i liked facebook-like

**Comment by fildunsky** [comment]
P.S. Can we make notification less blockchain-like and more human-like? I mean all that links are saying nothing most of the time.

- What if we will display post headers instead of generated-long-links-with-d95a3f98746638e8477-at-the-end?

- What if we will add post cover images in the right corner? Will it slowdown Surfer a lot?

**Comment by talhasch** [comment]
yeah, you are right. its look like a little bit primitive. 

in order to not slowdown surfer we need to make it with backend services. it has to be find relations in database....

but it is a little bit out of this context.

lets track it under another issue.

**Comment by fildunsky** [comment]
Can we make user notification filter choice to be saved by the way? I mean by default it shows `All Notifications` filter, when I choose `Replies` and open any other page in Surfer second time I open this popover I see `All notifications` again but would be handy to have it saved at least for the current session.

**Comment by talhasch** [comment]
yes, we can
