### ISSUE TITLE
esteem-surfer Automatically logs me out

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-surfer#135]
#### Expected behavior
After an account  is logged in, it shouldn't log the user out automatically. 

#### Actual behavior
The latest version of eSteem-Surfer logs me out with this error ```Looks like your steem connect access token has expired. Please login again.```

#### How to reproduce
- Download/Launch the latest version of eSteem-Surfer then login.
- scroll, click on tabs until this error ```Looks like your steem connect access token has expired. Please login again.``` pops up.

* App version: eSteem Surfer v  1.0.10
* Operating system: Windows 10 (64-bit)

#### Recording Of The Bug
https://youtu.be/TaxIm603OQI

**Comment by feruzm** [comment]
This is expected behavior for security reasons and only users signed in via Steemconnect should see this messages.

**Comment by realrufans** [comment]
So it means I can't use surfer comfortably anymore? It feels loging  my account out

**Comment by feruzm** [comment]
@realrufans you can use it comfortably, logout happens because steemconnect gives you access token during login which expires after 7 days. It is because of security reasons steemconnect requires you to relogin so new access token can be fetched. You could however use traditional login that will keep your keys locally encrypted on your device and it never expires or logs you out.

**Comment by realrufans** [comment]
Okay I will try it later 👍
