### ISSUE TITLE
Unable to upload image with same filename

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-surfer#140]
Sometimes I am uploading images into editor for posts and then realizing to change/tweak some content of that image, editing in Photoshop and saving using same filename. In this case I can not upload it second time until I'll rename it.

**Can we add some uploading check?**
- if the file has same name and same size then just give already uploaded image from Gallery
- if the name is same but size is different then allow upload again

P.S. This seems to be true only if last uploaded image is still there in the code of editor. Once I remove it I can reupload file with same filename...

**Comment by talhasch** [comment]
is your second image (with same file name) similar to first image?

**Comment by fildunsky** [comment]
Nope, I am editing this image in Photoshop, saving under same filename and then can not reupload so I have to change filename everytime

**Comment by talhasch** [comment]
hmmm 🤔 i don't clearly remember our image backend. do you have any idea why it might happen? @feruzm

**Comment by feruzm** [comment]
It might be caching issue on UI part. Backend upload doesn't restrict same filename uploads because it will be renamed on backend anyway. But there is one check, if you rename filename and content of image remains same without any edits on content/image itself, then upload will result same link because images are same files. It shouldn't cause above issue though.

**Comment by fildunsky** [comment]
Once I save draft and open it again only after that I can upload edited images with same filename. Just checked again...
